version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "flask-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-127a0yefuhpfg"
s3_prefix = "flask-aws"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ExecEnv=\"prod\" LotsOfListsTableName=\"lots-of-lists\""
