SECRET_KEY = b'1234'

AWS_BUCKET_NAME='raz_flask_files'
AWS_ACCESS_KEY='AKIA3DB7W7XK5DWO7DPS'
AWS_SECRET_ACCESS_KEY='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'
AWS_DOMAIN=http://raz_flask_files.s3.amazonaws.com/